version: '3.10'

services:

  database:

    build:
      context: ./.db/
    container_name: database
    tty: true
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .secret/db.env
    ports:
      - 3306:3306